/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.swamp.tank;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) throws Exception{
        
    }

    public static void main(String[] args) {
        launch(args);
    }

}
